const productos = [
    {id:1,
     name:'Buzo Negro',
     category:'buzo',
     stock:20,
     price:5000,
     img:'https://saborstore.com/wp-content/uploads/2022/04/Hoodie-Drop-Negro-Verde.jpg',
     description :'Buzo hecho con el algodón de mejor calidad y el mejor diseño'},
    {id:2,
     name:'Remera Negra',
     category:'remera',
     stock:17,
     price:2000,
     img:'https://saborstore.com/wp-content/uploads/2022/04/Remera-Drop-Negro-Violeta-Frente.jpg',
     description :'Remera Negra de la mejor calidad,un ajuste perfecto, el mejor precio y las mas facheras'},
    {id:3,
     name:'Pantalón Negro',
     category:'pantalon',
     stock:15,
     price:3500,
     img:'https://saborstore.com/wp-content/uploads/2021/11/Recto-Work-221-600x600.jpg',
     description :'Pantalon Negro de corte recto,super comodo, de la mejor calidad y el mejor precio'},
    {id:4,
     name:'Medias Rojas',
     category:'medias',
     stock:10,
     price:800,
     img:'https://saborstore.com/wp-content/uploads/2022/05/Medias-Square-Rojas-2.jpg',
     description :'Medias super comodas, el mejor ajuste, el mejor precio y las mas facheras'},
     {id:5,
      name:'Buzo Azul',
      category:'buzo',
      stock:20,
      price:5000,
      img:'https://saborstore.com/wp-content/uploads/2022/05/Hoodie-Americano.jpg',
      description :'Buzo azul con lineas rojas, la mejor calidad, el mejor precio y los mas facheros que viste'},
     {id:6,
      name:'Buzo Verde',
      category:'buzo',
      stock:20,
      price:5000,
      img:'https://saborstore.com/wp-content/uploads/2022/05/Hoodie-SBR-Verde.jpg',
      escription :'Buzo verde muy piola de la mejor calidad, el mejor precio y los mas facheros que viste'},
     {id:7,
      name:'Buzo Naranja',
     category:'buzo',
     stock:20,
     price:5000,
     img:'https://saborstore.com/wp-content/uploads/2022/05/Hoodie-Logo-Naranja.jpg',
     description :'Buzo naranja muy piola de la mejor calidad, el mejor precio y los mas facheros que viste'},
     {id:8,
     name:'Buzo Beige',
     category:'buzo',
     stock:20,
     price:5000,
     img:'https://saborstore.com/wp-content/uploads/2022/05/Hoodie-Logo-Vison.jpg',
     description :'Buzo beige muy piola de la mejor calidad, el mejor precio y los mas facheros que viste'},
     {id:9,
     name:'Jogger Negro',
     category:'pantalon',
     stock:15,
     price:3500,
     img:'https://saborstore.com/wp-content/uploads/2022/04/Jogger-TAG-Negro-Frente.jpg',
     description :'Jogger negro super comodo y abrigado, la mejor calidad y el mejor precio'},
     {id:10,
     name:'Pantalón Caqui',
     category:'pantalon',
     stock:15,
     price:3500,
     img:'https://saborstore.com/wp-content/uploads/2022/05/PANT-CAQUI-x1000.jpg',
     description :'Pantalon Caqui de corte recto,super comodo, de la mejor calidad y el mejor precio'},
     {id:11,
     name:'Pantalón Blanco',
     category:'pantalon',
     stock:15,
     price:3500,
     img:'https://saborstore.com/wp-content/uploads/2021/11/workblancofrente.jpg',
     description :'Pantalon Blanco de corte recto,super comodo, de la mejor calidad y el mejor precio'},
     {id:12,
      name:'Pantalón Lila',
      category:'pantalon',
      stock:15,
      price:3500,
      img:'https://saborstore.com/wp-content/uploads/2021/12/pant-baggy-lavanda-4.jpg',
      description :'Pantalon Lila de estilo Baggy,super comodo, de la mejor calidad y el mejor precio'},
      {id:13,
       name:'Medias Naranja',
       category:'medias',
       stock:10,
       price:800,
       img:'https://saborstore.com/wp-content/uploads/2021/12/Tag-Naranja.jpg',
       description :'Medias super comodas, el mejor ajuste, el mejor precio y las mas facheras'},
      {id:14,
       name:'Medias Lila',
       category:'medias',
       stock:10,
       price:800,
       img:'https://saborstore.com/wp-content/uploads/2021/12/Tag-Lila.jpg',
       description :'Medias super comodas, el mejor ajuste, el mejor precio y las mas facheras'},
       {id:15,
        name:'Medias Lilas',
        category:'medias',
        stock:10,
        price:800,
        img:'https://saborstore.com/wp-content/uploads/2022/05/Medias-Square-Blancas.jpg',
        description :'Medias super comodas, el mejor ajuste, el mejor precio y las mas facheras'},
       {id:16,
        name:'Medias Negras',
        category:'medias',
        stock:10,
        price:800,
        img:'https://saborstore.com/wp-content/uploads/2022/05/Medias-Square-Negras.jpg',
        description :'Medias super comodas, el mejor ajuste, el mejor precio y las mas facheras'},
       {id:17,
        name:'Chomba Negra',
        category:'remera',
        stock:17,
        price:2000,
        img:'https://saborstore.com/wp-content/uploads/2019/01/Chomba-NEGRA.jpg',
        description :'Chomba Negra de la mejor calidad,un ajuste perfecto, el mejor precio y las mas facheras'},
        {id:18,
         name:'Chomba Blanca',
         category:'remera',
         price:2000,
         img:'https://saborstore.com/wp-content/uploads/2021/12/Chomba-Blanca-Arena-x1000.jpg',
         description :'Chomba Blanca de la mejor calidad,un ajuste perfecto, el mejor precio y las mas facheras'},
        {id:19,
         name:'Remera Beige',
         category:'remera',
         stock:17,
         price:800,
         img:'https://saborstore.com/wp-content/uploads/2021/12/Rem-Square-Arena.jpg',
         description :'Remera Beige de la mejor calidad,un ajuste perfecto, el mejor precio y las mas facheras'},
        {id:20,
         name:'Remera Blanca',
         category:'remera',
         stock:17,
         price:2000,
         img:'https://saborstore.com/wp-content/uploads/2022/04/Rem-Drop-Blanca-Naranja-Frente.jpg',
         description :'Remera Blanca de la mejor calidad,un ajuste perfecto, el mejor precio y las mas facheras'},
        
         
]

export const getProducts = () =>{
    return new Promise ((prendas)=> {
        setTimeout(()=>{
            prendas(productos)
        },500)
    })
}

export const getProductById = (id) =>{
    return new Promise (resolve=> {
        setTimeout(()=>{
            resolve(productos.find(prod => prod.id === parseInt(id)))
        },500)
    })
}

export const getProductsByCategory=(categoryId) => {
    return new Promise(resolve =>{
        setTimeout(()=>{
            resolve(productos.filter(prod => prod.category === categoryId))
        })
    })
}